# Generated by Django 6.0.7 on 2026-07-10 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of customer, e.g., Shops, Events, Distributors', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this customer classification', null=True)),
            ],
            options={
                'verbose_name': 'Customer Type',
                'verbose_name_plural': 'Customer Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date the expense was incurred')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent', max_digits=10)),
                ('category', models.CharField(choices=[('Fuel', 'Fuel'), ('Electricity', 'Electricity'), ('Maintenance', 'Maintenance'), ('Salary', 'Salary'), ('Other', 'Other')], help_text='Category classification for breakdown analysis', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Details of the expenditure', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name or company name of the customer', max_length=150)),
                ('phone', models.CharField(blank=True, help_text='Contact number for notifications or billing queries', max_length=20, null=True)),
                ('custom_id', models.CharField(help_text="Custom unique ID string (e.g., 'FT-8821') to match visual UI layout", max_length=20, unique=True, verbose_name='Custom ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_type', models.ForeignKey(help_text='Classification for this customer', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='dashboard.customertype')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date the sale occurred')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity sold (bags or blocks)', max_digits=10)),
                ('unit_type', models.CharField(choices=[('Bags', 'Bags'), ('Blocks', 'Blocks')], default='Bags', help_text='Measurement unit: Bags or Blocks', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per bag/block', max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Pending', help_text='Payment state: Paid, Pending, or Overdue', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(help_text='Customer associated with this sale', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='dashboard.customer')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
