# Generated by Django 6.0.7 on 2026-07-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_expense_date_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(help_text='Quantity sold (bags or kg)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_type',
            field=models.CharField(choices=[('Bags', 'Bags'), ('Kg', 'Kg')], default='Bags', help_text='Measurement unit: Bags or Kg', max_length=10),
        ),
    ]
